name: Build & Deploy Docs
on:
  push:
    branches: [ main ]        # or Main – must match exactly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build docs
        run: docfx build -o _site --template default

      # NEW — bundle the _site folder as artifact "github-pages"
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site         # must match build output
          name: github-pages    # deploy‑pages looks for this exact name

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
