name: Build & Deploy Docs

on:
  push:
    branches: [ main ]
    paths: [ '**.md', 'docs/**', 'docfx.json', 'src/**', '.github/workflows/docs.yml' ]

# required scopes for Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # ---------- Build job ----------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Generate API metadata
        run: docfx metadata

      - name: Build docs
        run: docfx build -o _site --template default

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site          # folder containing index.html

  # ---------- Deploy job ----------
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
