name: Build & Deploy Docs
on:
  push:
    branches: [ main ]          # or Main – match the real name

# NEW ─────────────────────────────────────────────────────────
permissions:
  contents: read        # checkout & read the repo
  pages: write          # create/update the Pages deployment
  id-token: write       # OIDC token required by deploy-pages
# ─────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build docs
        run: docfx build -o _site --template default

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site          # folder that contains index.html
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
